### DISCUSSION TITLE
Production

### DISCUSSION THREAD

**Discussion by olaronymax** [mindsdb/mindsdb#6962] [Get help]
hello!  I'm using MindsDB and I would like to know how to put it into production using Docker Compose and Nginx. Is there any tutorial available?

**Comment by ianu82** [comment]
Hey @olaronymax, I don't believe we have a tutorial but we'd be happy to assist. @ZoranPandovski or @martyna-mindsdb will be able to advise. 

Would love to know all about your use case if you're able to share :-)

**Reply by janbrb** [reply]
Hi @ianu82 , I am also looking for a production ready build using Docker Compose. I tried pretty much anything I could find but cant get it to run. 

I tried 23.10.5.0 and latest. With or without MDB_CONFIG_CONTENT env var.

`MDB_CONFIG_CONTENT={"api": {"http": {"host": "0.0.0.0", "port": "47334"}, "mysql": {"host": "0.0.0.0", "port": "47335", "database": "mindsdb", "ssl": true}, "mongodb": {"host": "0.0.0.0", "port": "47336", "database": "mindsdb"}}}`

Testet both locally on port 47334 and via traefik routing on domain (all routers and services working)

Hope I can get some help here and try it out in a current project! :)

```
version: "3.7"
services:
  mindsdb:
    image: mindsdb/mindsdb:23.10.5.0
    command: bash -c "python3 -m mindsdb --api=http,mysql,mongodb"
    volumes:
      - mindsdb_data:/root 
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: any 
      placement:
        constraints: [node.role == manager]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.mindsdb.rule=Host(`example.com`)"
      - "traefik.http.services.mindsdb.loadbalancer.server.port=47334"
      - "traefik.http.routers.mindsdb.entrypoints=web,websecure"
    ports:
      - "47334:47334"
      - "47335:47335"
      - "47336:47336"

networks:
  proxy:
    external: true

volumes:
  mindsdb_data:
```
